# Generated by Django 4.0.4 on 2023-05-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_clase_profesor_id_seccion_profesor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('credencial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
    ]
